apiVersion: v1
kind: Pod
metadata:
  name: test-pod 
  namespace: default
spec:
    nodeName: preprod-worker1
    containers:
    - name: date
      image: busybox
    securityContext:
      privileged: true 
    volumeMounts:
    - mountPath: /data 
      name: hostpath-privileged
  securityContext: {}
  volumes:
    - name: hostpath-privileged
      persistentVolumeClaim:
        claimName: foo-pvc
